"""add order_by desc in relation user and tasks

Revision ID: 8753b222e8dc
Revises: 9279aebef531
Create Date: 2024-08-21 00:35:15.754959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8753b222e8dc'
down_revision: Union[str, None] = '9279aebef531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
