version: "3.1"

services:
  app:
    build:
      context: .
    ports:
      - 8001:8000
    volumes:
      - ./var/lib/jenkins/workspace/multipurpose_system/app:/var/
    depends_on:
      - postgresql
    env_file:
      - ./.env
  
  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - ./app